In [1]:
# Creating graphs with Pytorch
import torch
def compute_z(a,b,c):
    r1=torch.sub(a,b)
    r2=torch.mul(r1,2)
    r3=torch.add(r2,c)
    return r3

print(compute_z(torch.tensor(1.0),torch.tensor(2.0),torch.tensor(3.0)))
print(compute_z(torch.tensor([1.0,2.0]),torch.tensor([2.0,3.0]),torch.tensor([3.0,4.0])))
print(compute_z(torch.tensor([[1.0,2.0],[2.0,3.0]]),torch.tensor([[2.0,3.0],[3.0,4.0]]),torch.tensor([[3.0,4.0],[4.0,5.0]])))

tensor(1.)
tensor([1., 2.])
tensor([[1., 2.],
        [2., 3.]])


In [4]:
# Xavier Glorot initialization
import torch.nn as nn
torch.manual_seed(0)
w=torch.empty(3,5)
print(w)
nn.init.xavier_uniform_(w)
print(w)

tensor([[ 0.0000e+00,  0.0000e+00,  4.3332e+15,  3.2506e-41,  6.9513e+17],
        [ 3.2506e-41, -7.0998e+19,  4.1750e-41,  1.4013e-45,  0.0000e+00],
        [ 2.1019e-44,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]])
tensor([[-0.0065,  0.4646, -0.7128, -0.6373, -0.3336],
        [ 0.2322, -0.0172,  0.6867, -0.0769,  0.2292],
        [-0.2617, -0.1702, -0.8274, -0.5736, -0.3570]])


In [12]:
# computing gradient with respect to trainable var
x=torch.tensor([1.4])
y=torch.tensor([2.1])
w=torch.tensor(1.0,requires_grad=True)
b=torch.tensor(.5,requires_grad=True)
z=torch.add(torch.mul(w,x),b)
loss=(y-z).pow(2).sum()
loss.backward()
print(w.grad)
print(b.grad)

tensor(-0.5600)
tensor(-0.4000)
